# You can find color codes here: https://minecraft.tools/en/color-code.php
# Formatting comes after the color! &d&l will work, but not &l&d.
# MiniMessage formatting IS supported: https://docs.adventure.kyori.net/minimessage.html#template
# MiniMessage allows you to make rainbow colors and gradients!
# HEX/RGB colors ARE supported. (Only the MOTD)
# Hex format: &#FFFFFF
# Placeholders: %online% (Players online)
# %max% (Server max slots)
# %newline% adds a newline to your MOTD.
# %tps% shows the tps (Paper only)
description:
  activated: true
  text:
    - #- "&7&l&o2B &6It wouldn’t be 2B without a new owner %newline%&7&l&o2T"
      "&7&l&o2B &6Africans cant swim! %newline%&7&l&o2T"
    - "&7&l&o2B &6fit was here %newline%&7&l&o2T"
    - "&7&l&o2B &6HAUSEMASTER TAKE MY MONEY!!! %newline%&7&l&o2T"
    - #- "&b&l2B2T &62b2t < &6&l2b2t Germany"
      "&7&l&o2B &6SMIB SMIB SMIB SMIB %newline%&7&l&o2T"
    - "&7&l&o2B &6You will be alone in the end... %newline%&7&l&o2T"
    - "&7&l&o2B &6server is full %newline%&7&l&o2T"
    - "&7&l&o2B &6maybe hitler was right %newline%&7&l&o2T"
    - "&7&l&o2B &6yiff %newline%&7&l&o2T"
    # the 8b8t wont be visible but its funny
    - "&7&l&o2B &6TudbuT is the king of &k8b8t %newline%&7&l&o2T"
    - "&7&l&o2B &6TudbuT is the king of &k2b2t %newline%&7&l&o2T"
    - "&7&l&o2B &6TTC on top! %newline%&7&l&o2T"
    - "&7&l&o2B &6e621 :flushed: %newline%&7&l&o2T"
    #2843501 on e621
    - "&7&l&o2B &62843501 on e621 thank me later %newline%&7&l&o2T"
# Not supported on: Spigot (Paper works), Sponge
version:
  # The version name is shown if the version of the client doesn't match the version of the server.
  # %aftericon% adds a bunch of spaces so the text is after the icon. (Only for protocol)
  name:
    activated: false
    text: "&12B2TProxy"
  # Dangerous! This can show a wrong server version to the client.
  # When the client is on a different protocol, it will show the version name set above.
  protocol:
    activated: false
    value: 1

players:
  # Override your actual player count
  # Not supported on: Spigot (Paper works)
  online:
    activated: false
    value: 0
  # Override your max player count
  max:
    activated: false
    value: 10
  # Will show ??? as the player count.
  # Not supported on: Spigot (Paper works)
  hide: false
  # Box shown when you hover over the player count
  # Not supported on: Spigot (Paper works)
  sample:
    # Restores the vanilla behavior for the sample box.
    # The name of every player on the server will be shown in the sample box.
    # Overrides the text feature from below.
    vanilla:
      activated: false
      hidden:
        - "&b&l2B2T"
    activated: false
    text:
      - "&32B8t"

# The image of a server in the server list.
favicon:
  activated: false
  # Favicons are stored in the /plugins/PistonMOTD/favicons folder.
  # Favicons are 64x64 pixels and must be PNG. The file name does not matter for random mode.
  # Valid: RANDOM, SINGLE
  mode: RANDOM
  # The single favicon shown when SINGLE is selected.
  single: example.png

# Extensions to the functionality of PistonMOTD
extensions:
  # Extensions for vanishing plugins
  vanish:
    # Support for SuperVanish. Hide players from the player count/sample on Bukkit.
    supervanish: false
    # Support for PremiumVanish. Hide players from the player count/sample on Bukkit AND BungeeCord. (Premium plugin)
    premiumvanish: false
    # Hide players from the vanilla player sample feature.
    hideSample: true
    # Hide players from the online player count. (Most vanish plugins already have that built in)
    hideCount: false

# Advanced features that should not be messed with unless you know what you're doing.
advanced:
  # If activated the server will only be shown as supported for the following protocols.
  supportedProtocol:
    activated: false
    unsupportedNumber: -1 # Shown when the protocol is not supported.
    # The supported protocol versions.
    # Protocol version numbers can be found here: https://wiki.vg/Protocol_version_numbers
    numbers:
      - 757
      - 756
